# Generated by Django 3.0.6 on 2020-07-04 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('white', '0002_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=400)),
                ('marca', models.CharField(blank=True, max_length=40)),
                ('modelo', models.CharField(blank=True, max_length=40)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='white.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=400)),
                ('data_entrega', models.DateField()),
                ('data_conserto', models.DateField()),
                ('resolucao', models.CharField(blank=True, max_length=400)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='white.Produto')),
            ],
        ),
    ]
