# Generated by Django 3.0.6 on 2020-07-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white', '0003_problema_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='data_conserto',
            field=models.DateField(null=True),
        ),
    ]
